openapi: 3.0.0
info:
  title: Yelp
  description: The API for Yelp, the popular review website.
  version: 1.0.0
servers:
  - url: https://demo.stepzen.net
tags:
  - name: queries
    description: Sample queries for you to try.
paths:
  /studio/yelp/__graphql:
    post:
      tags:
        - queries
      summary: yelp_search
      description: Search the Yelp API.
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
